### PR TITLE
Fix subsampling and add columns to subsample analysis output with unique names for both variables and the edge

### PR DESCRIPTION
**Pull request by macovskym**
Depends on #20.

### CODE REVIEW

**Comment by macovskym** [comment]
Variable 1 & 2 columns should be first

**Comment by macovskym** [comment]
Need to fix numpy string truncation issue

**Comment by macovskym** [comment]
Columns reordered. Truncation issue fixed in #20.

**Comment by bruceamm** [comment]
Correct unique cell names added in appropriate columns.

**Pull request merged**
